//! Schreier-Sims algorithm for permutation groups.
//!
//! Builds a base and strong generating set (BSGS) along the natural base
//! `0, 1, ..., degree - 1`. Level `i` holds the strong generators fixing
//! `0..i` pointwise together with a transversal of the orbit of `i` under
//! them. Every group element then factors uniquely as
//! `compose(compose(u_k, u_{k-1}), ..., u_0)` with `u_i` in transversal `i`,
//! which gives membership testing by sifting, the group order as a product
//! of orbit sizes, and duplicate-free enumeration.

use crate::permutation::{compose, identity, inverse, is_identity, Permutation};
use std::collections::hash_map::{Entry, HashMap};

/// One level of the stabilizer chain.
#[derive(Debug, Clone)]
pub struct Level {
    /// Strong generators fixing every point before this level's base point.
    pub generators: Vec<Permutation>,
    /// For each point `y` in the orbit of the base point, an element mapping the base point to `y`.
    pub transversal: HashMap<usize, Permutation>,
}

/// A base and strong generating set for a permutation group.
#[derive(Debug, Clone)]
pub struct BSGS {
    degree: usize,
    levels: Vec<Level>,
}

/// Computes a BSGS for the group generated by `generators` acting on `0..degree`.
pub fn schreier_sims(generators: &[Permutation], degree: usize) -> BSGS {
    let mut bsgs = BSGS::trivial(degree);
    for g in generators {
        let (residual, level) = bsgs.sift_from(g, 0);
        if !is_identity(&residual) {
            bsgs.add_generator(&residual, 0, level);
        }
    }
    bsgs.close();
    bsgs
}

impl BSGS {
    /// The trivial group on `degree` points.
    pub fn trivial(degree: usize) -> Self {
        let levels = (0..degree)
            .map(|i| Level {
                generators: Vec::new(),
                transversal: HashMap::from([(i, identity(degree))]),
            })
            .collect();
        Self { degree, levels }
    }

    /// Number of points the group acts on.
    pub fn degree(&self) -> usize {
        self.degree
    }

    /// The stabilizer chain, one level per point.
    pub fn levels(&self) -> &[Level] {
        &self.levels
    }

    /// Base points with a nontrivial orbit.
    pub fn base(&self) -> Vec<usize> {
        (0..self.degree)
            .filter(|&i| self.levels[i].transversal.len() > 1)
            .collect()
    }

    /// The strong generating set.
    pub fn strong_generators(&self) -> &[Permutation] {
        &self.levels[0].generators
    }

    /// Order of the group.
    pub fn order(&self) -> usize {
        self.levels.iter().map(|l| l.transversal.len()).product()
    }

    /// Sifts `g` through the chain, returning the residual. The residual is the
    /// identity exactly when `g` is a group element.
    pub fn sift(&self, g: &[usize]) -> Permutation {
        self.sift_from(g, 0).0
    }

    /// Membership test.
    pub fn contains(&self, g: &[usize]) -> bool {
        g.len() == self.degree && is_identity(&self.sift(g))
    }

    /// Every group element exactly once.
    pub fn elements(&self) -> Vec<Permutation> {
        let mut acc = vec![identity(self.degree)];
        for level in self.levels.iter().rev() {
            acc = acc
                .iter()
                .flat_map(|e| level.transversal.values().map(move |u| compose(e, u)))
                .collect();
        }
        acc
    }

    /// Sifts from `start`, returning the residual and the level it dropped out at.
    fn sift_from(&self, g: &[usize], start: usize) -> (Permutation, usize) {
        let mut h = g.to_vec();
        for (i, level) in self.levels.iter().enumerate().skip(start) {
            let Some(u) = level.transversal.get(&h[i]) else {
                return (h, i);
            };
            h = compose(&h, &inverse(u));
        }
        (h, self.degree)
    }

    /// Adds `g`, which fixes every point before `last`, to levels `first..=last`.
    fn add_generator(&mut self, g: &[usize], first: usize, last: usize) {
        for l in first..=last.min(self.degree - 1) {
            self.levels[l].generators.push(g.to_vec());
            self.rebuild_transversal(l);
        }
    }

    /// Sifts Schreier generators until every level's generators generate the
    /// stabilizer of the level above.
    fn close(&mut self) {
        let mut changed = true;
        while changed {
            changed = false;
            for level in 0..self.degree {
                let gens = self.levels[level].generators.clone();
                let reps: Vec<Permutation> =
                    self.levels[level].transversal.values().cloned().collect();
                for u in &reps {
                    for s in &gens {
                        let us = compose(u, s);
                        let Some(v) = self.levels[level].transversal.get(&us[level]) else {
                            continue;
                        };
                        let schreier = compose(&us, &inverse(v));
                        let (residual, next) = self.sift_from(&schreier, level + 1);
                        if !is_identity(&residual) {
                            self.add_generator(&residual, level + 1, next);
                            changed = true;
                        }
                    }
                }
            }
        }
    }

    /// Recomputes the orbit and transversal of `level` from its generators.
    fn rebuild_transversal(&mut self, level: usize) {
        let gens = &self.levels[level].generators;
        let mut transversal = HashMap::from([(level, identity(self.degree))]);
        let mut queue = vec![level];
        while let Some(x) = queue.pop() {
            let Some(ux) = transversal.get(&x).cloned() else {
                continue;
            };
            for g in gens {
                if let Entry::Vacant(e) = transversal.entry(g[x]) {
                    e.insert(compose(&ux, g));
                    queue.push(g[x]);
                }
            }
        }
        self.levels[level].transversal = transversal;
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use itertools::Itertools;

    #[test]
    fn trivial_group() {
        let bsgs = schreier_sims(&[], 3);
        assert_eq!(bsgs.order(), 1);
        assert!(bsgs.base().is_empty());
        assert!(bsgs.contains(&[0, 1, 2]));
        assert!(!bsgs.contains(&[1, 0, 2]));
    }

    #[test]
    fn symmetric_group_s5() {
        let bsgs = schreier_sims(&[vec![1, 0, 2, 3, 4], vec![1, 2, 3, 4, 0]], 5);
        assert_eq!(bsgs.order(), 120);
        for p in (0..5).permutations(5) {
            assert!(bsgs.contains(&p));
        }
        let mut elements = bsgs.elements();
        elements.sort();
        elements.dedup();
        assert_eq!(elements.len(), 120);
    }

    #[test]
    fn alternating_group_a4() {
        let bsgs = schreier_sims(&[vec![1, 2, 0, 3], vec![0, 2, 3, 1]], 4);
        assert_eq!(bsgs.order(), 12);
        assert!(bsgs.contains(&[1, 0, 3, 2]));
        assert!(bsgs.contains(&[0, 3, 1, 2]));
        assert!(!bsgs.contains(&[1, 0, 2, 3]));
        let mut elements = bsgs.elements();
        elements.sort();
        elements.dedup();
        assert_eq!(elements.len(), 12);
    }

    #[test]
    fn riemann_slot_group() {
        let gens = vec![vec![1, 0, 2, 3], vec![0, 1, 3, 2], vec![2, 3, 0, 1]];
        let bsgs = schreier_sims(&gens, 4);
        assert_eq!(bsgs.order(), 8);
        assert!(bsgs.contains(&[3, 2, 1, 0]));
        assert!(!bsgs.contains(&[0, 2, 1, 3]));
    }

    #[test]
    fn generators_that_fix_early_points() {
        let gens = vec![
            vec![0, 1, 3, 2, 4],
            vec![0, 2, 3, 4, 1],
            vec![1, 0, 2, 3, 4],
        ];
        let bsgs = schreier_sims(&gens, 5);
        assert_eq!(bsgs.order(), 120);
        assert_eq!(bsgs.elements().len(), 120);
    }

    #[test]
    fn sift_of_non_member_is_unchanged_when_it_drops_at_level_zero() {
        let bsgs = schreier_sims(&[vec![1, 0, 2, 3], vec![0, 2, 1, 3]], 4);
        assert!(bsgs.contains(&[2, 0, 1, 3]));
        assert_eq!(bsgs.sift(&[3, 1, 2, 0]), vec![3, 1, 2, 0]);
    }
}
