//! Tensor slot symmetries.
//!
//! Each symmetry is a set of signed permutations of the tensor's slots that
//! generate part of its slot symmetry group. The sign records whether the
//! tensor picks up a factor of `-1` under the permutation.

use crate::error::{validate_permutation, ButlerPortugalError, Result};
use crate::permutation::{identity, Permutation};
use std::collections::HashSet;

/// A symmetry of a tensor under permutation of its slots.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Symmetry {
    /// Invariant under any permutation of these slots.
    Symmetric { indices: Vec<usize> },
    /// Changes sign under odd permutations of these slots.
    Antisymmetric { indices: Vec<usize> },
    /// Invariant under exchanging whole pairs of slots, as in `R_abcd = R_cdab`.
    /// Nothing is implied about the order within a pair.
    SymmetricPairs { pairs: Vec<(usize, usize)> },
    /// Invariant under cyclic rotation of these slots.
    Cyclic { indices: Vec<usize> },
    /// Generated by explicit signed permutations of all slots.
    Custom {
        permutations: Vec<Permutation>,
        signs: Vec<i32>,
    },
}

impl Symmetry {
    /// Symmetric under any permutation of `indices`.
    ///
    /// ```rust
    /// use butler_portugal::Symmetry;
    ///
    /// let sym = Symmetry::symmetric(vec![0, 1, 2]); // T_abc = T_bac = T_cab = ...
    /// ```
    pub fn symmetric(indices: Vec<usize>) -> Self {
        Self::Symmetric { indices }
    }

    /// Antisymmetric under any permutation of `indices`.
    ///
    /// ```rust
    /// use butler_portugal::Symmetry;
    ///
    /// let asym = Symmetry::antisymmetric(vec![0, 1]); // T_ab = -T_ba
    /// ```
    pub fn antisymmetric(indices: Vec<usize>) -> Self {
        Self::Antisymmetric { indices }
    }

    /// Symmetric under exchange of whole pairs.
    ///
    /// ```rust
    /// use butler_portugal::Symmetry;
    ///
    /// // Riemann tensor: R_abcd = R_cdab
    /// let sym = Symmetry::symmetric_pairs(vec![(0, 1), (2, 3)]);
    /// ```
    pub fn symmetric_pairs(pairs: Vec<(usize, usize)>) -> Self {
        Self::SymmetricPairs { pairs }
    }

    /// Symmetric under cyclic rotation of `indices`.
    ///
    /// ```rust
    /// use butler_portugal::Symmetry;
    ///
    /// let cyc = Symmetry::cyclic(vec![0, 1, 2]); // T_abc = T_bca = T_cab
    /// ```
    pub fn cyclic(indices: Vec<usize>) -> Self {
        Self::Cyclic { indices }
    }

    /// Generated by explicit signed permutations. Each permutation must have
    /// length equal to the tensor rank and each sign must be `1` or `-1`.
    pub fn custom(permutations: Vec<Permutation>, signs: Vec<i32>) -> Self {
        Self::Custom {
            permutations,
            signs,
        }
    }

    /// Signed permutation generators of this symmetry for a tensor of the given rank.
    pub fn generators(&self, rank: usize) -> Result<Vec<(Permutation, i32)>> {
        let transpositions = |slots: &[usize], sign: i32| -> Result<Vec<(Permutation, i32)>> {
            check_slots(slots, rank)?;
            Ok(slots
                .windows(2)
                .map(|w| {
                    let mut p = identity(rank);
                    p.swap(w[0], w[1]);
                    (p, sign)
                })
                .collect())
        };
        match self {
            Self::Symmetric { indices } => transpositions(indices, 1),
            Self::Antisymmetric { indices } => transpositions(indices, -1),
            Self::SymmetricPairs { pairs } => {
                let flat: Vec<usize> = pairs.iter().flat_map(|&(a, b)| [a, b]).collect();
                check_slots(&flat, rank)?;
                Ok(pairs
                    .windows(2)
                    .map(|w| {
                        let mut p = identity(rank);
                        p.swap(w[0].0, w[1].0);
                        p.swap(w[0].1, w[1].1);
                        (p, 1)
                    })
                    .collect())
            }
            Self::Cyclic { indices } => {
                check_slots(indices, rank)?;
                if indices.len() < 2 {
                    return Ok(Vec::new());
                }
                let mut p = identity(rank);
                for (i, &slot) in indices.iter().enumerate() {
                    p[slot] = indices[(i + 1) % indices.len()];
                }
                Ok(vec![(p, 1)])
            }
            Self::Custom {
                permutations,
                signs,
            } => {
                if permutations.len() != signs.len() {
                    return Err(ButlerPortugalError::InvalidSymmetry(format!(
                        "{} permutations but {} signs",
                        permutations.len(),
                        signs.len()
                    )));
                }
                for p in permutations {
                    validate_permutation(p, rank)?;
                }
                if let Some(s) = signs.iter().find(|&&s| s != 1 && s != -1) {
                    return Err(ButlerPortugalError::InvalidSymmetry(format!(
                        "sign {s} is not 1 or -1"
                    )));
                }
                Ok(permutations
                    .iter()
                    .cloned()
                    .zip(signs.iter().copied())
                    .collect())
            }
        }
    }
}

fn check_slots(slots: &[usize], rank: usize) -> Result<()> {
    if let Some(&s) = slots.iter().find(|&&s| s >= rank) {
        return Err(ButlerPortugalError::IndexOutOfBounds {
            index: s,
            max: rank,
        });
    }
    let unique: HashSet<usize> = slots.iter().copied().collect();
    if unique.len() != slots.len() {
        return Err(ButlerPortugalError::InvalidSymmetry(format!(
            "repeated slot in {slots:?}"
        )));
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn symmetric_generators_are_signed_plus() {
        let gens = Symmetry::symmetric(vec![0, 1, 2]).generators(3).unwrap();
        assert_eq!(gens, vec![(vec![1, 0, 2], 1), (vec![0, 2, 1], 1)]);
    }

    #[test]
    fn antisymmetric_generators_are_signed_minus() {
        let gens = Symmetry::antisymmetric(vec![3, 1]).generators(4).unwrap();
        assert_eq!(gens, vec![(vec![0, 3, 2, 1], -1)]);
    }

    #[test]
    fn pair_exchange_does_not_swap_within_pairs() {
        let gens = Symmetry::symmetric_pairs(vec![(0, 1), (2, 3)])
            .generators(4)
            .unwrap();
        assert_eq!(gens, vec![(vec![2, 3, 0, 1], 1)]);
    }

    #[test]
    fn cyclic_generator() {
        let gens = Symmetry::cyclic(vec![0, 1, 2]).generators(4).unwrap();
        assert_eq!(gens, vec![(vec![1, 2, 0, 3], 1)]);
    }

    #[test]
    fn out_of_range_slot_is_an_error() {
        assert!(Symmetry::symmetric(vec![0, 5]).generators(2).is_err());
        assert!(Symmetry::antisymmetric(vec![0, 0]).generators(2).is_err());
        assert!(Symmetry::custom(vec![vec![1, 0]], vec![2])
            .generators(2)
            .is_err());
        assert!(Symmetry::custom(vec![vec![1, 0, 2]], vec![1])
            .generators(2)
            .is_err());
    }
}
